import Providers from "@/providers";
import "./globals.css";
import { Inter } from "next/font/google";
import Toaster from "@/components/Shared/Toaster/Toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HatMat",
  description: "Generated by create next app",

};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" data-theme="light">
      <Providers>
        <body
          suppressHydrationWarning={true}
          className={`${inter.className} scrollbar select-none`}
        >
          {children}
          <Toaster />
        </body>
      </Providers>
    </html>
  );
};
export default RootLayout;
