import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HatMat",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" data-theme="light">
      <body suppressHydrationWarning={true} className={inter.className}>{children}</body>
    </html>
  );
};
export default RootLayout;
